### ISSUE TITLE
Remove chrN_random,ChrUn,chrM reads before using Q

### ISSUE THREAD

**Issue by CTLife** [charite/Q#7]
Hi, 
Is it necessary for peak calling of histone modifications ChIP-seq data to remove the mapped reads on chrN_random, ChrUn and chrM before running Q?

Thank you!

**Comment by hansenp** [comment]
Hi,

those "irregular" chromosomes are primarily unplaced contigs. See here:

http://ucscbrowser.genap.ca/cgi-bin/hgGateway
https://genome.ucsc.edu/FAQ/FAQdownloads.html

In my experience it is better to discard those chromosomes, because they are often the source of artifacts that can ruin quality metrics, e.g. the relative strand correlation (RSC), which depends on the height of the phantom peak in the cross-correlation plot, which in turn depends on wether or not those chromosomes are included. Even worse, including those chromosomes may lead to violation of null model assumptions for statistical tests, bacause it is often the case that many reads map to the same location.

Best,
Peter

**Comment by CTLife** [comment]
Thank you!  Peter.
