### ISSUE TITLE
Errors for some samples

### ISSUE THREAD

**Issue by CTLife** [charite/Q#8]
H3K4me3 peaks in Mouse (mm10) or C.elegans (WBcel235) are identified by using Q  v1.3.0 with default parameters (except for -wbt, -wbc), but there is a error for some samples, such as: 
### Error in `Q': double free or corruption (!prev): 0x00000000055ac290 **\*            ,  9-Q-run1-1.sh: line 14:  6190 Aborted          (core dumped)

Although this error doesn't affect the results, but I guess that you want to figure it out in next version of Q.

BTW:  my H3K4me3 ChIP-seq data is paired-end (by Illumina HiSeq X Ten)  and sorted BAM files based on genomic positions are the values of --treatment-sample and  --control-sample.

File 9-Q-run1-1.sh is available:
https://github.com/CTLife/TEMP/blob/master/peakCallerQ/9-Q-run1-1.sh

**Comment by hansenp** [comment]
Hi CTLife,

thank you for reporting this bug. The script fails in line 14, which corresponds to

'5_spr5-AA_Rep1/5_spr5-AA_Rep1'.

In order to fix the bug I need more information. If I had the BAM files

5-FinalBAM/3-Bowtie/5_spr5-AA-H3K4me3-CTTGTA-GGCTAC_Rep1.bam
5-FinalBAM/3-Bowtie/5_Input-spr5-AA-TAGCTT_Rep1.bam

it would be the best. Is it possible to provide me with these two files?

Otherwise, the files 

9-Q/run1/5_spr5-AA-H3K4me3-CTTGTA-GGCTAC_Rep1.log.txt
9-Q/run1/5_spr5-AA_Rep1/5_spr5-AA_Rep1-Q-binding-characteristics.R

could contain useful information. Could you provide me with these files?

Best,
Peter
